FROM python:3.11.6 as requirements-stage

WORKDIR /tmp

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock* /tmp/

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.11.6

WORKDIR /backendcode

COPY --from=requirements-stage /tmp/requirements.txt /backendcode/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /backendcode/requirements.txt

COPY ./app /backendcode/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]